// Generate a data file that maps CDN image URLs to their dimensions.
// Run this after optimise-images.ts so the dimensions match the files that
// will actually be uploaded to R2.
// Usage: node scripts/generate-image-dimensions.ts
import sharp from "sharp";
import { readdir, writeFile } from "node:fs/promises";
import { extname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("../", import.meta.url));
const INPUT_DIR = ROOT + "optimised-bucket";
const OUTPUT_FILE = ROOT + "src/data/image-dimensions.ts";
const CDN_BASE = "https://cdn.m4yank.com";

const IMAGE_EXTENSIONS = new Set([
  ".png",
  ".jpg",
  ".jpeg",
  ".webp",
  ".gif",
  ".avif",
]);

async function* walk(dir: string): AsyncGenerator<string> {
  const entries = await readdir(dir, { withFileTypes: true });
  for (const entry of entries) {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) {
      yield* walk(path);
    } else if (entry.isFile()) {
      yield path;
    }
  }
}

const dimensions: Record<string, { width: number; height: number }> = {};

for await (const file of walk(INPUT_DIR)) {
  const ext = extname(file).toLowerCase();
  if (!IMAGE_EXTENSIONS.has(ext)) continue;

  const rel = relative(INPUT_DIR, file);
  const url = `${CDN_BASE}/${rel.replace(/\\/g, "/")}`;

  const { width, height } = await sharp(file).metadata();
  if (!width || !height) {
    console.warn(`Could not read dimensions for ${rel}`);
    continue;
  }

  dimensions[url] = { width, height };
  console.log(`${url} → ${width}x${height}`);
}

const fileContent = `// Auto-generated by scripts/generate-image-dimensions.ts.
// Do not edit manually. Run: node scripts/generate-image-dimensions.ts

export type ImageDimensions = {
  width: number;
  height: number;
};

export const imageDimensions: Record<string, ImageDimensions> = ${JSON.stringify(dimensions, null, 2)};

export function getImageDimensions(src: string): ImageDimensions | undefined {
  return imageDimensions[src];
}
`;

await writeFile(OUTPUT_FILE, fileContent);
console.log(
  `\nWrote ${Object.keys(dimensions).length} image dimensions to ${OUTPUT_FILE}`,
);
