// Auto-generated by scripts/generate-image-dimensions.ts.
// Do not edit manually. Run: node scripts/generate-image-dimensions.ts

export type ImageDimensions = {
  width: number;
  height: number;
};

export const imageDimensions: Record<string, ImageDimensions> = {
  "https://cdn.m4yank.com/assets/blog/sync-task-scheduler/1d.webp": {
    width: 1200,
    height: 675,
  },
  "https://cdn.m4yank.com/assets/blog/sync-task-scheduler/2d.webp": {
    width: 1200,
    height: 1384,
  },
  "https://cdn.m4yank.com/assets/blog/sync-task-scheduler/3d.webp": {
    width: 914,
    height: 1063,
  },
  "https://cdn.m4yank.com/assets/blog/sync-task-scheduler/4d.webp": {
    width: 1200,
    height: 1251,
  },
  "https://cdn.m4yank.com/assets/notebook/1-art.webp": {
    width: 1200,
    height: 900,
  },
  "https://cdn.m4yank.com/assets/notebook/2-art.webp": {
    width: 1200,
    height: 1600,
  },
  "https://cdn.m4yank.com/assets/notebook/3-art.webp": {
    width: 1200,
    height: 900,
  },
  "https://cdn.m4yank.com/assets/notebook/4-art.webp": {
    width: 960,
    height: 1280,
  },
  "https://cdn.m4yank.com/assets/notebook/5-art.webp": {
    width: 1200,
    height: 900,
  },
  "https://cdn.m4yank.com/assets/projects/redis-go/1.webp": {
    width: 1200,
    height: 900,
  },
  "https://cdn.m4yank.com/assets/projects/termcall/1.webp": {
    width: 1200,
    height: 900,
  },
  "https://cdn.m4yank.com/assets/work/gdgc-pccoe/1.webp": {
    width: 1200,
    height: 693,
  },
};

export function getImageDimensions(src: string): ImageDimensions | undefined {
  return imageDimensions[src];
}
